repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
    - id: ruff-format
      name: ruff format
      language: system
      entry: uv run --dev ruff format
      pass_filenames: false

    - id: ruff-lint
      name: ruff lint
      language: system
      entry: uv run --dev ruff check --fix
      pass_filenames: false

    - id: mypy-type-check
      name: mypy type check
      language: system
      entry: uv run --dev mypy .
      pass_filenames: false

    - id: pytest-run-unit-tests
      name: pytest run unit tests
      language: system
      entry: uv run --dev pytest
      pass_filenames: false
